name: D-dmd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Alicedbg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
    - name: 'Test'
      run: dub test -c debugger --compiler=dmd
  Alicedump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
    - name: 'Test'
      run: dub test -c dumper --compiler=dmd
  Simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
    - name: 'Build'
      run: dub build -c simple --compiler=dmd
