name: Simple

on: [ push, pull_request ]

# Tests ensures the project builds and executes unittest.
# The entry points are rather minimal.
jobs:
  Build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1
    - name: Build
      run: dub build -c simple
