name: Tests

on: [ push, pull_request ]

# Tests ensures the project builds and executes unittest.
# The entry points are rather minimal.
jobs:
  Alicedbg:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        dc: [ dmd-latest, ldc-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}
    - name: Test Alicedbg
      run: dub test -c debugger
  Alicedump:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]
        dc: [ dmd-latest, ldc-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}
    - name: Test Alicedump
      run: dub test -c dumper